from enum import Enum


class ProcessingState(Enum):
    """
    Potential results of conflation
    """
    NO = 1
    CHECKED_POSSIBLE = 2
    CONFLATED = 3
    ERROR_END_POINTS_FAR_APART = 4
    ERROR_GEOMETRY_WRONG = 5
    ERROR_SHARED_WAY_NOT_FOUND = 6
    ERROR_WAY_NOT_FOUND = 7
    ERROR_MULTIPLE_SHARED_WAYS = 8
    ERROR_MULTIPLE_SINGLE_WAY = 9
    ERROR_NODES_WITH_TAGS = 10
    ERROR_NATIONAL_BORDER = 11
    ERROR_UNEXPECTED_TAG = 12
    ERROR_NODE_IN_OTHER_WAYS = 13
    ERROR_NODE_IN_NATIONAL_BORDER = 14
    ERROR_NODE_IN_OTHER_RELATION = 15
    ERROR_NODE_IN_NATIONAL_RELATION = 16
    ERROR_INVALID_SHAPE = 17
    ERROR_CLOSED_SHAPE = 18
    ERROR_OVERLAPPING_WAYS = 19
    ERROR_TOO_MANY_NODES = 20